version: "3.7"
services:
  server:
    build: .
    command: sh /entrypoint.bash
    volumes:
      - ${HOST_SDK_ROOT:?err}/doc-src:/docs-src:ro
      - ${HOST_SDK_ROOT:?err}/docs:/_output # output
    ports:
      - "${HOST_PORT_SPACE:?err}111:80"
