from typing import Any

from django import forms
from django.contrib import admin
from guardian.forms import GroupObjectPermissionsForm as GroupObjectPermissionsForm
from guardian.forms import UserObjectPermissionsForm as UserObjectPermissionsForm
from guardian.shortcuts import get_group_perms as get_group_perms
from guardian.shortcuts import get_groups_with_perms as get_groups_with_perms
from guardian.shortcuts import get_perms_for_model as get_perms_for_model
from guardian.shortcuts import get_user_perms as get_user_perms
from guardian.shortcuts import get_users_with_perms as get_users_with_perms

class AdminUserObjectPermissionsForm(UserObjectPermissionsForm):
    def get_obj_perms_field_widget(self): ...

class AdminGroupObjectPermissionsForm(GroupObjectPermissionsForm):
    def get_obj_perms_field_widget(self): ...

class GuardedModelAdminMixin:
    change_form_template: str
    obj_perms_manage_template: str
    obj_perms_manage_user_template: str
    obj_perms_manage_group_template: str
    user_can_access_owned_objects_only: bool
    user_owned_objects_field: str
    user_can_access_owned_by_group_objects_only: bool
    group_owned_objects_field: str
    include_object_permissions_urls: bool
    def get_queryset(self, request): ...
    def get_urls(self): ...
    def get_obj_perms_base_context(self, request, obj): ...
    def obj_perms_manage_view(self, request, object_pk): ...
    def get_obj_perms_manage_template(self): ...
    def obj_perms_manage_user_view(self, request, object_pk, user_id): ...
    def get_obj_perms_manage_user_template(self): ...
    def get_obj_perms_user_select_form(self, request): ...
    def get_obj_perms_group_select_form(self, request): ...
    def get_obj_perms_manage_user_form(self, request): ...
    def obj_perms_manage_group_view(self, request, object_pk, group_id): ...
    def get_obj_perms_manage_group_template(self): ...
    def get_obj_perms_manage_group_form(self, request): ...

class GuardedModelAdmin(GuardedModelAdminMixin, admin.ModelAdmin): ...

class UserManage(forms.Form):
    user: Any
    def clean_user(self): ...

class GroupManage(forms.Form):
    group: Any
    def clean_group(self): ...
