from guardian.conf import settings as settings
from guardian.core import ObjectPermissionChecker as ObjectPermissionChecker
from guardian.ctypes import get_content_type as get_content_type
from guardian.exceptions import WrongAppError as WrongAppError
from typing import Any

def check_object_support(obj): ...
def check_user_support(user_obj): ...
def check_support(user_obj, obj): ...

class ObjectPermissionBackend:
    supports_object_permissions: bool
    supports_anonymous_user: bool
    supports_inactive_user: bool
    def authenticate(self, request, username: Any | None = ..., password: Any | None = ...) -> None: ...
    def has_perm(self, user_obj, perm, obj: Any | None = ...): ...
    def get_all_permissions(self, user_obj, obj: Any | None = ...): ...
