from guardian.ctypes import get_content_type as get_content_type
from guardian.utils import get_group_obj_perms_model as get_group_obj_perms_model, get_identity as get_identity, get_user_obj_perms_model as get_user_obj_perms_model
from typing import Any

class ObjectPermissionChecker:
    def __init__(self, user_or_group: Any | None = ...) -> None: ...
    def has_perm(self, perm, obj): ...
    def get_group_filters(self, obj): ...
    def get_user_filters(self, obj): ...
    def get_user_perms(self, obj): ...
    def get_group_perms(self, obj): ...
    def get_perms(self, obj): ...
    def get_local_cache_key(self, obj): ...
    def prefetch_perms(self, objects): ...
