from guardian.exceptions import GuardianError as GuardianError
from guardian.utils import get_40x_or_None as get_40x_or_None
from typing import Any

def permission_required(perm, lookup_variables: Any | None = ..., **kwargs): ...
def permission_required_or_403(perm, *args, **kwargs): ...
def permission_required_or_404(perm, *args, **kwargs): ...
