class GuardianError(Exception): ...
class NotUserNorGroup(GuardianError): ...
class ObjectNotPersisted(GuardianError): ...
class WrongAppError(GuardianError): ...
class MixedContentTypeError(GuardianError): ...
class MultipleIdentityAndObjectError(GuardianError): ...
