from typing import Any

from django import forms
from guardian.shortcuts import assign_perm as assign_perm
from guardian.shortcuts import get_group_perms as get_group_perms
from guardian.shortcuts import get_perms_for_model as get_perms_for_model
from guardian.shortcuts import get_user_perms as get_user_perms
from guardian.shortcuts import remove_perm as remove_perm

class BaseObjectPermissionsForm(forms.Form):
    obj: Any
    def __init__(self, obj, *args, **kwargs) -> None: ...
    def get_obj_perms_field(self): ...
    def get_obj_perms_field_name(self): ...
    def get_obj_perms_field_label(self): ...
    def get_obj_perms_field_choices(self): ...
    def get_obj_perms_field_initial(self): ...
    def get_obj_perms_field_class(self): ...
    def get_obj_perms_field_widget(self): ...
    def are_obj_perms_required(self): ...
    def save_obj_perms(self) -> None: ...

class UserObjectPermissionsForm(BaseObjectPermissionsForm):
    user: Any
    def __init__(self, user, *args, **kwargs) -> None: ...
    def get_obj_perms_field_initial(self): ...
    def save_obj_perms(self) -> None: ...

class GroupObjectPermissionsForm(BaseObjectPermissionsForm):
    group: Any
    def __init__(self, group, *args, **kwargs) -> None: ...
    def get_obj_perms_field_initial(self): ...
    def save_obj_perms(self) -> None: ...
