from typing import Any

env: Any
DEBUG: bool
ANONYMOUS_USER_NAME: str
AUTH_USER_MODEL: str
GUARDIAN_MONKEY_PATCH: bool
INSTALLED_APPS: Any
AUTHENTICATION_BACKENDS: Any
MIDDLEWARE: Any
TEST_RUNNER: str
ROOT_URLCONF: str
SITE_ID: int
SECRET_KEY: Any
DATABASES: Any
TEMPLATES: Any
