# Generated by Django 3.2.11 on 2022-01-27 02:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_client_framework.models.abstract.model
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('django_client_framework', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchfeature',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='searchfeature',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='UserObjectPermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('object_pk', models.UUIDField(verbose_name='object ID')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.permission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=(models.Model, django_client_framework.models.abstract.model.__implements__, django_client_framework.models.abstract.model.IDCFModel),
        ),
        migrations.CreateModel(
            name='GroupObjectPermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('object_pk', models.UUIDField(verbose_name='object ID')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.permission')),
            ],
            bases=(models.Model, django_client_framework.models.abstract.model.__implements__, django_client_framework.models.abstract.model.IDCFModel),
        ),
        migrations.AddIndex(
            model_name='userobjectpermission',
            index=models.Index(fields=['content_type', 'object_pk'], name='django_clie_content_b379c5_idx'),
        ),
        migrations.AddConstraint(
            model_name='userobjectpermission',
            constraint=models.UniqueConstraint(fields=('user', 'permission', 'content_type', 'object_pk'), name='Make sure no duplicated user object permission entry is saved.'),
        ),
        migrations.AddIndex(
            model_name='groupobjectpermission',
            index=models.Index(fields=['content_type', 'object_pk'], name='django_clie_content_bb6e1e_idx'),
        ),
        migrations.AddConstraint(
            model_name='groupobjectpermission',
            constraint=models.UniqueConstraint(fields=('group', 'permission', 'content_type', 'object_pk'), name='Make sure no duplicated group object permission entry is saved.'),
        ),
    ]
