from typing import Any

ANONYMOUS_USER_NAME: Any
RENDER_403: Any
TEMPLATE_403: Any
RAISE_403: Any
RENDER_404: Any
TEMPLATE_404: Any
RAISE_404: Any
GET_INIT_ANONYMOUS_USER: Any
MONKEY_PATCH: Any
GET_CONTENT_TYPE: Any
AUTO_PREFETCH: Any
USER_OBJ_PERMS_MODEL: Any
GROUP_OBJ_PERMS_MODEL: Any

def check_configuration() -> None: ...
